# Generated by Django 3.2.15 on 2022-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulka',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('Nachinka', models.TextField()),
                ('text_ops', models.TextField()),
            ],
        ),
    ]
