# Generated by Django 3.2.15 on 2022-10-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0002_auto_20221028_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
