# Generated by Django 3.2.15 on 2022-10-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0003_alter_bulka_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulka',
            name='img',
            field=models.ImageField(default='.../static/css/logo.png', upload_to=''),
        ),
    ]
