# Generated by Django 3.2.15 on 2022-10-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0004_bulka_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulka',
            name='img',
        ),
        migrations.AddField(
            model_name='bulka',
            name='imgs',
            field=models.ImageField(default='/static/css/logo.png', upload_to=''),
        ),
    ]
