# Generated by Django 3.2.15 on 2022-10-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0005_auto_20221030_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='imgs',
            field=models.ImageField(default='/static/css/logo.png', upload_to='static/'),
        ),
    ]
