# Generated by Django 3.2.15 on 2022-10-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0007_alter_bulka_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='imgs',
            field=models.ImageField(default='/static/css/logo.png', upload_to='cacke/static/upload/'),
        ),
    ]
