# Generated by Django 3.2.15 on 2022-11-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0009_alter_bulka_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='imgs',
            field=models.ImageField(default='/static/css/logo.png', upload_to='./static/upload/'),
        ),
    ]
