# Generated by Django 3.2.15 on 2022-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0014_alter_bulka_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulka',
            name='id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
