# Generated by Django 3.2.15 on 2022-11-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0015_bulka_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bulka',
            name='name',
            field=models.TextField(),
        ),
    ]
