# Generated by Django 3.2.15 on 2022-11-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0016_auto_20221107_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulka',
            name='names',
            field=models.TextField(default=models.TextField()),
        ),
    ]
