# Generated by Django 3.2.15 on 2022-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cacke', '0017_bulka_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulka',
            name='names',
            field=models.TextField(),
        ),
    ]
